#!/bin/sh

dump(){
    t=$(LC_ALL=en_US.utf8 date +"%s-%3N")
    tmp_path=".hyprland_logger.tmp"
    res="$(hyprctl activewindow)"

    if [ "$res" = "Invalid" ]; then
        res=" title: Desktop
 pid: 00000
 class: Desktop"
    fi

    # title=$(echo "$res" | grep -E "*title" | sed 's/^[^:]*: //g') # Does not work if "title" is in title !
    # title=$(echo "$res" | jq -r '.title') # hyprctl activewindow -j
    # title=$(echo "$res" | awk -F': ' '/^[[:space:]]*title:/ {print $2}')
    # title=$(echo "$res" | sed -n 's/^[[:space:]]*title: //p')

    # Almost as fast, but stronger regex
    title=$(echo "$res" | sed -n 's/^[[:space:]]*title: //p')
    class=$(echo "$res" | sed -n 's/^[[:space:]]*class: //p')
    printf -v pid "%05d" "$(echo "$res" | sed -n 's/^[[:space:]]*pid: //p')" || printf -v pid "%05d" 0

    printf -v new "[$pid] [$class] $title"

    # echo "NEW : $new;"
    # echo "OLD : $(cat $tmp_path);"

    [ "$new" = "$(cat $tmp_path)" ] || echo "[$t] $new"
    echo $new > $tmp_path
}


handle() {
  case $1 in
    activewindow*) dump >> $filename ;;
  esac
}

filename="$(LC_ALL=en_US.utf8 date +"%d-%m-%Y_%Hh%Mm%S").wins"
echo -en "Starting at $(LC_ALL=en_US.utf8 date +"%a %b %d %T %Y")\n\n" > $filename

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
